### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by russellhoff** [mimicmobile/okhttp-oauth2-client#8]
Is it posible to hide/show progress bars within a OAuthResponseCallback?

Thank you!!

**Comment by corcoran** [comment]
I'm not sure what you mean by this.  There's no real progress to measure.  The library makes a request and when the request is complete returns the result.  There's no "steps" to use as a progressive indicator.

**Comment by russellhoff** [comment]
When I make a request, I usually show a dialogto inform the user that a task is being done. So, when firing the OAuthResponseCallback, I'd want to hide the dialog. The issue is that yesterday I tried this and an error message was thrown in Logcat (can't remember the exact text, I'll text you later on).

**Comment by corcoran** [comment]
Ah I see. The callback acts like any other callback so it seems like your issues lies entirely outside of the library.

**Comment by russellhoff** [comment]
Thanks @corcoran , that's what I supposed.

**Comment by russellhoff** [comment]
This is the piece of code:

```
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(com.joninx.euskofest.R.layout.activity_login);

        Hawk.init(getApplicationContext()).build();

        progressDialog = new ProgressDialog(this);
        progressDialog.setTitle("Iniciando sesión");
        progressDialog.setMessage("Cargando...");
        progressDialog.setProgressStyle(ProgressDialog.STYLE_SPINNER);
        progressDialog.setCancelable(false);
        progressDialog.hide();
        // ...
}
```

```
client.requestAccessToken(new OAuthResponseCallback() {

                @Override
                public void onResponse(OAuthResponse response) {
                    progressDialog.dismiss();
                    if (response.isSuccessful()) {
                        String accessToken = response.getAccessToken();
                        String refreshToken = response.getRefreshToken();

                        Hawk.put("accessToken", accessToken);
                        Hawk.put("refreshToken", refreshToken);

                        finish();
                        Intent i = new Intent(LoginActivity.this, MainActivity.class);
                        LoginActivity.this.startActivity(i);
                    } else {
                        OAuthError error = response.getOAuthError();
                        String errorMsg = error.getError();
                        mPasswordView.setError(getString(com.joninx.euskofest.R.string.error_incorrect_password));
                        mPasswordView.requestFocus();
                    }
                }

            });
```

And this is the stack trace:
```
E/AndroidRuntime: FATAL EXCEPTION: Thread-7
                  Process: euskofest.joninx.com.euskofest, PID: 2034
                  android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
                      at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8443)
                      at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1418)
                      at android.view.View.requestLayout(View.java:23203)
                      at android.view.View.requestLayout(View.java:23203)
                      at android.view.View.requestLayout(View.java:23203)
                      at android.view.View.requestLayout(View.java:23203)
                      at android.view.View.requestLayout(View.java:23203)
                      at android.view.View.requestLayout(View.java:23203)
                      at android.view.View.requestLayout(View.java:23203)
                      at android.widget.ScrollView.requestLayout(ScrollView.java:2455)
                      at android.view.View.requestLayout(View.java:23203)
                      at android.view.View.requestLayout(View.java:23203)
                      at android.view.View.requestLayout(View.java:23203)
                      at android.view.View.requestLayout(View.java:23203)
                      at android.widget.Editor.setErrorIcon(Editor.java:579)
                      at android.widget.Editor.setError(Editor.java:563)
                      at android.widget.TextView.setError(TextView.java:6813)
                      at android.widget.TextView.setError(TextView.java:6798)
                      at com.joninx.euskofest.activities.LoginActivity$2.onResponse(LoginActivity.java:148)
                      at ca.mimic.oauth2library.OAuth2Client$2.run(OAuth2Client.java:102)
                      at java.lang.Thread.run(Thread.java:764)
```

148 line of LoginActivity.java is related to`mPasswordView.setError(getString(com.joninx.euskofest.R.string.error_incorrect_password));`
